name: Sync compose-spec json

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  schema:
    name: Update Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download schema
        run: curl -fSL -o schema/compose-spec.json https://raw.githubusercontent.com/compose-spec/compose-go/main/schema/compose-spec.json

      - name: Show diff
        run: git diff schema/compose-spec.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          title: Update compose-spec.json
          commit-message: Update compose-spec.json
          signoff: true
          branch: compose-spec-json
